# Generated by Django 4.2.15 on 2024-09-02 10:14

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('article', '0007_articlepost_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags. 多个标签之间使用英文逗号隔开', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
