# Generated by Django 4.2.15 on 2024-09-03 10:35

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_alter_articlepost_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='正文内容'),
        ),
    ]
