# Generated by Django 4.2.15 on 2024-09-14 02:42

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0009_alter_articlepost_body'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jmxs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, help_text='文件名称地址', null=True, upload_to='jmx/', verbose_name='文件地址')),
                ('desc', models.CharField(blank=True, help_text='文件描述', max_length=100, null=True, verbose_name='描述')),
                ('column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jmxs', to='article.articlecolumn')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags. 多个标签之间使用英文逗号隔开', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
