# Generated by Django 4.2.15 on 2024-09-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_method', models.CharField(max_length=20, verbose_name='Upload Method')),
                ('file', models.FileField(blank=True, null=True, upload_to='{app_name}/', verbose_name='工具地址')),
            ],
        ),
    ]
