# Generated by Django 4.2.15 on 2024-09-10 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tools',
            name='upload_method',
        ),
    ]
