# Generated by Django 4.2.15 on 2024-09-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_remove_tools_upload_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tools',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='工具地址'),
        ),
    ]
