# Generated by Django 4.2.15 on 2024-09-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_alter_tools_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='tools',
            name='desc',
            field=models.CharField(blank=True, help_text='文件描述', max_length=100, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='tools',
            name='file',
            field=models.FileField(blank=True, help_text='文件名称地址', null=True, upload_to='files/', verbose_name='工具地址'),
        ),
    ]
